version: "3.8"

services:
  nginx:
    image: docker-website-nginx-html-advanced
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./site:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always